package com.pro;
// Generated 22 Apr, 2015 3:48:22 AM by Hibernate Tools 4.3.1



/**
 * Candidate generated by hbm2java
 */
public class Candidate  implements java.io.Serializable {


     private int voterId;
     private Constituency constituency;
     private Party party;
     private String name;
     private String agenda;
     private String asset;
     private int voteN;
     private String qualification;
     private String active;
     private String new_;
     private int ftime;
     private String pass;

    public Candidate() {
    }

    public Candidate(int voterId, Constituency constituency, Party party, String name, String agenda, String asset, int voteN, String qualification, String active, String new_, int ftime, String pass) {
       this.voterId = voterId;
       this.constituency = constituency;
       this.party = party;
       this.name = name;
       this.agenda = agenda;
       this.asset = asset;
       this.voteN = voteN;
       this.qualification = qualification;
       this.active = active;
       this.new_ = new_;
       this.ftime = ftime;
       this.pass = pass;
    }
   
    public int getVoterId() {
        return this.voterId;
    }
    
    public void setVoterId(int voterId) {
        this.voterId = voterId;
    }
    public Constituency getConstituency() {
        return this.constituency;
    }
    
    public void setConstituency(Constituency constituency) {
        this.constituency = constituency;
    }
    public Party getParty() {
        return this.party;
    }
    
    public void setParty(Party party) {
        this.party = party;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getAgenda() {
        return this.agenda;
    }
    
    public void setAgenda(String agenda) {
        this.agenda = agenda;
    }
    public String getAsset() {
        return this.asset;
    }
    
    public void setAsset(String asset) {
        this.asset = asset;
    }
    public int getVoteN() {
        return this.voteN;
    }
    
    public void setVoteN(int voteN) {
        this.voteN = voteN;
    }
    public String getQualification() {
        return this.qualification;
    }
    
    public void setQualification(String qualification) {
        this.qualification = qualification;
    }
    public String getActive() {
        return this.active;
    }
    
    public void setActive(String active) {
        this.active = active;
    }
    public String getNew_() {
        return this.new_;
    }
    
    public void setNew_(String new_) {
        this.new_ = new_;
    }
    public int getFtime() {
        return this.ftime;
    }
    
    public void setFtime(int ftime) {
        this.ftime = ftime;
    }
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }




}


